#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PROCESSAMENTO COMPLETO DOS DADOS DAS 63 ESCOLAS
Atualização total das bases centrais de dados
"""

import pandas as pd
import json
import os
from datetime import datetime


def processar_dados_completos_63_escolas():
    """Processa e salva os dados completos das 63 escolas"""
    print("📊 PROCESSANDO DADOS COMPLETOS DAS 63 ESCOLAS")
    print("=" * 70)

    # Dados das 63 escolas conforme fornecido
    dados_escolas = [
        [
            "JOAO CARREIRA",
            "PRIMAVERA, SN, CAMBIRA, CEP: 16900970",
            "Quilombola/Assentamento",
            "ANDRADINA",
            "Rural",
            "Andradina",
            "10a Rua R Regente Feijo, 2160, Vila Mineira, Andradina, SP, CEP: 16901908",
            "Andradina",
            21.00,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-21.0112896, -51.46931458",
            "-20.896505, -51.3742765",
            "ANDRADINA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ASSENTAMENTO ZUMBI DOS PALMARES",
            "AREA RURAL, AREA RURAL DE IARAS, CEP: 18779899",
            "Quilombola/Assentamento",
            "IARAS",
            "Rural",
            "Avare",
            "Avenida Pref. Misael Eufrásio Leal, 857 - Vila Aires, Avaré - SP, 18705-050",
            "Avare",
            44.17,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.75668907, -49.13655853",
            "-23.0998, -48.9267",
            "AVARE",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ALDEIA NIMUENDAJU",
            "POSTO INDIGENA NIMUENDAJU, SN, ALDEIA NIMUENDAJU, CEP: 16680000",
            "Indígena",
            "AVAI",
            "Rural",
            "Bauru",
            "Rua Campos Salles, 9 - 43, Vila Falcao, Bauru, SP, CEP: 17050000",
            "Bauru",
            29.40,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.29116058, -49.37730026",
            "-22.3233112, -49.0940288",
            "BAURU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA EKERUA",
            "ALDEIA EKERUA, SN, ALDEIA EKERUA, CEP: 16680000",
            "Indígena",
            "AVAI",
            "Rural",
            "Bauru",
            "Rua Campos Salles, 9 - 43, Vila Falcao, Bauru, SP, CEP: 17050000",
            "Bauru",
            29.24,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.2747097, -49.37297058",
            "-22.3233112, -49.0940288",
            "BAURU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA TEREGUA",
            "ALDEIA TEREGUA, SN, LARANJEIRAS, CEP: 16680000",
            "Indígena",
            "AVAI",
            "Rural",
            "Bauru",
            "Rua Campos Salles, 9 - 43, Vila Falcao, Bauru, SP, CEP: 17050000",
            "Bauru",
            34.86,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.16006088, -49.38312149",
            "-22.3233112, -49.0940288",
            "BAURU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA KOPENOTI",
            "Posto Indigena Kopenoti, S/N - Aldeia Kopenoti, Avaí - SP, 16680-000",
            "Indígena",
            "AVAI",
            "Rural",
            "Bauru",
            "Rua Campos Salles, 9 - 43, Vila Falcao, Bauru, SP, CEP: 17050000",
            "Bauru",
            27.16,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.264515, -49.35027069",
            "-22.3233112, -49.0940288",
            "BAURU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA RENASCER",
            "CORCOVADO, SN, CORCOVADO, CEP: 11682520",
            "Indígena",
            "UBATUBA",
            "Urbana",
            "Caraguatatuba",
            "Avenida Alagoas, 539, Indaia, Caraguatatuba, SP, CEP: 11665159",
            "Caraguatatuba",
            29.12,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.47613907, -45.19160843",
            "-23.6204, -45.4132",
            "CARAGUATATUBA",
            "Escola indígena em zona urbana",
        ],
        [
            "ALDEIA BOA VISTA",
            "PROMIRIM, PROMIRIM, CEP: 11697404",
            "Indígena",
            "UBATUBA",
            "Urbana",
            "Caraguatatuba",
            "Avenida Alagoas, 539, Indaia, Caraguatatuba, SP, CEP: 11665160",
            "Caraguatatuba",
            54.17,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.37615967, -44.96944046",
            "-23.6204, -45.4132",
            "CARAGUATATUBA",
            "Escola indígena em zona urbana",
        ],
        [
            "EE IDALICIO MENDES  LIMA O SR BAIANO DA AGROVILA I",
            "PIRITUBA, SN, 13 DE MAIO, CEP: 18400970",
            "Quilombola/Assentamento",
            "ITAPEVA",
            "Rural",
            "Itapeva",
            "Rua Rtorquato Raimundo, 96, Jardim Ferrari, Itapeva, SP, CEP: 18405010",
            "Itapeva",
            27.43,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.1126194, -49.11140823",
            "-23.9849105, -48.8803886",
            "ITAPEVA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "TXONDARO TEKOA  MBAE",
            "VICINAL, BAIRRO DOS VITOR, CEP: 18490000",
            "Indígena",
            "BARAO DE ANTONINA",
            "Rural",
            "Itarare",
            "Rua Dr Rubens Lobo Ribeiro, 310, Cruzeiro, Itarare, SP, CEP: 18460540",
            "Itarare",
            60.64,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.61064911, -49.58242035",
            "-24.1083, -49.3342",
            "ITARARE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA KARUGWA",
            "VICINAL, SN, BAIRRO DOS VITOR, CEP: 18490000",
            "Indígena",
            "BARAO DE ANTONINA",
            "Rural",
            "Itarare",
            "Rua Dr Rubens Lobo Ribeiro, 310, Cruzeiro, Itarare, SP, CEP: 18460540",
            "Itarare",
            61.64,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.60279083, -49.58737946",
            "-24.1083, -49.3342",
            "ITARARE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA YWY PYHAU",
            "BAIRRO DOS VITOR, DOS VITOR, CEP: 18490000",
            "Indígena",
            "BARAO DE ANTONINA",
            "Rural",
            "Itarare",
            "Rua Dr Rubens Lobo Ribeiro, 310, Cruzeiro, Itarare, SP, CEP: 18460540",
            "Itarare",
            61.61,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.5999794, -49.57976913",
            "-24.1083, -49.3342",
            "ITARARE",
            "Escola indígena em zona rural",
        ],
        [
            "AGROVILA III",
            "AGROVILA III, SN, AGROVILA III, CEP: 18440000",
            "Quilombola/Assentamento",
            "ITABERA",
            "Rural",
            "Itarare",
            "Rua Dr Rubens Lobo Ribeiro, 310, Cruzeiro, Itarare, SP, CEP: 18460540",
            "Itarare",
            28.04,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.01605034, -49.08214188",
            "-24.1083, -49.3342",
            "ITARARE",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ALDEIA TEKOAPORA",
            "BAIRRO VOLTA GRANDE, SN, VOLTA GRANDE, CEP: 18480000",
            "Indígena",
            "ITAPORANGA",
            "Rural",
            "Itarare",
            "Rua Dr. Rubéns Lôbo Ribeiro, 310 - Bairro Ginasio, Itararé - SP, 18460-000",
            "Itarare",
            50.17,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.6990509, -49.54547119",
            "-24.1083, -49.3342",
            "ITARARE",
            "Escola indígena em zona rural",
        ],
        [
            "COMUNIDADE NOSSA SENHORA APARECIDA",
            "BR 153, SN, FAZENDA REUNIDAS, CEP: 16370000",
            "Quilombola/Assentamento",
            "PROMISSAO",
            "Rural",
            "Lins",
            "Rua Luiz Gama, 681 - Centro, Lins - SP, 16400-045",
            "Lins",
            38.24,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-21.33078957, -49.79145813",
            "-21.6741873, -49.7518932",
            "LINS",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ALDEIA GWAWIRA",
            "ALDEIA GWAWIRA, SN, SABAUNA, CEP: 11920000",
            "Indígena",
            "IGUAPE",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            65.04,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.79512024, -47.76939011",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA ITAPUA",
            "MUNICIPAL, SN, PRAIA DO LESTE, CEP: 11920000",
            "Indígena",
            "IGUAPE",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            44.74,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.68457985, -47.50952148",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "TAGUATO AGUIA",
            "DO ICAPARA, SN, TOCA DO BUGIO, CEP: 11920000",
            "Indígena",
            "IGUAPE",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            44.87,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.68473053, -47.51789856",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA CAPOEIRAO",
            "ALDEIA CAPOEIRAO, SN, KM 93, CEP: 11760000",
            "Indígena",
            "ITARIRI",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            34.30,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.30809021, -47.11671829",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA RIO DO AZEITE",
            "RIO DO AZEITE, SN, RIO DO AZEITE, CEP: 11760000",
            "Indígena",
            "ITARIRI",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            29.13,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.33348083, -47.17166138",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA URUITY",
            "ALDEIA URUITY, SN, BAIRRO MUSACEA, CEP: 11850000",
            "Indígena",
            "MIRACATU",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            13.10,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.26409912, -47.32629013",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA DJAIKOATY",
            "ALDEIA DJAIKOATY, SN, BAIRRO LAMBARI, CEP: 11850000",
            "Indígena",
            "MIRACATU",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            12.63,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.20033073, -47.36891937",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "KO E JU",
            "ALDEIA INDIGENA AMBA PORA, KM 372, SANTA RITA DO RIBEIRA, CEP: 11850000",
            "Indígena",
            "MIRACATU",
            "Rural",
            "Miracatu",
            "Avenida Doná Evarista de Castro Ferreira - Centro, Miracatu - SP, 11850-000",
            "Miracatu",
            18.33,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.15617943, -47.33876038",
            "-24.2854, -47.4588",
            "MIRACATU",
            "Escola indígena em zona rural",
        ],
        [
            "LIDIA SANAE OYA",
            "PROJETO AGROVILA ROSANELA, SN, AGROVILA ROSANELA, CEP: 19275000",
            "Quilombola/Assentamento",
            "EUCLIDES DA CUNHA PAULISTA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            65.91,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-22.57377052, -52.47143936",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "MARIA ANTONIA ZANGARINI FERREIRA PROFESSORA",
            "GLEBA XV DE NOVEMBRO, SN, SETOR IV, CEP: 19275000",
            "Quilombola/Assentamento",
            "EUCLIDES DA CUNHA PAULISTA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            82.67,
            "Média (50-100km)",
            "MÉDIA - Monitorar",
            "-22.47491074, -52.68555069",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ASSENTAMENTO SANTA CLARA",
            "ASSENTAMENTO CHE GUEVARA, 0, SANTA CLARA, CEP: 19260000",
            "Quilombola/Assentamento",
            "MIRANTE DO PARANAPANEMA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            28.03,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.51530647, -52.03659058",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "FAZENDA SAO BENTO",
            "HAROLDINA, ENGENHEIRO VERAS, CEP: 19260000",
            "Quilombola/Assentamento",
            "MIRANTE DO PARANAPANEMA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            17.99,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.43954086, -51.9817009",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "GLEBA XV DE NOVEMBRO",
            "GLEBA XV DE NOVEMBRO SII, SN, GLEBA XV DE NOVEMBRO, CEP: 19273000",
            "Quilombola/Assentamento",
            "ROSANA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            91.11,
            "Média (50-100km)",
            "MÉDIA - Monitorar",
            "-22.46820068, -52.77148056",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "RIBEIRINHOS",
            "GLEBA XV DE NOVEMBRO, SN, GLEBA XV DE NOVEMBRO, CEP: 19273000",
            "Quilombola/Assentamento",
            "ROSANA",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            83.26,
            "Média (50-100km)",
            "MÉDIA - Monitorar",
            "-22.45060921, -52.69752884",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ROMILDA LAZARA PILLON DOS SANTOS PROFESSORA",
            "ASSENTAMENTO AGUA SUMIDA, SN, AGUA SUMIDA, CEP: 19280000",
            "Quilombola/Assentamento",
            "TEODORO SAMPAIO",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            41.85,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-22.31339073, -52.31266022",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ASSENTAMENTO SANTA ZELIA",
            "ASSENTAMENTO SANTA ZELIA, SN, SANTA ZELIA, CEP: 19280000",
            "Quilombola/Assentamento",
            "TEODORO SAMPAIO",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            54.04,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-22.37401009, -52.42435074",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "ANTONIA BINATO SILVA VO NINA",
            "ALCIDIA, SN, DESTILARIA ALCIDIA, CEP: 19280000",
            "Quilombola/Assentamento",
            "TEODORO SAMPAIO",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            63.41,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-22.35367012, -52.51908112",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "FRANCISCO FERREIRA DE SOUZA PROFESSOR",
            "GLEBA RIBEIRAO BONITO, SN, RIBEIRAO BONITO, CEP: 19280000",
            "Quilombola/Assentamento",
            "TEODORO SAMPAIO",
            "Rural",
            "Mirante do Paranapanema",
            "Rua Antônio Erisvaldo da Silva, 597 - Sol Nascente, Mirante do Paranapanema - SP, 19260-000",
            "Mirante do Paranapanema",
            53.77,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-22.48542023, -52.38634109",
            "-22.2847, -51.9088",
            "MIRANTE DO PARANAPANEMA",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "DJEKUPE AMBA ARANDY",
            "TURISTICA DO JARAGUA, 3710, VILA JARAGUA, CEP: 5161000",
            "Indígena",
            "SAO PAULO",
            "Urbana",
            "Norte 1",
            "Rua Faustolo, 281 - Água Branca, São Paulo - SP, 05041-000",
            "São Paulo",
            9.43,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.46372986, -46.75337982",
            "-23.524, -46.6883",
            "NORTE 1",
            "Escola indígena em zona urbana",
        ],
        [
            "INDIA MARIA ROSA",
            "POSTO INDIGENA ICATU, SN, GUAPORANGA, CEP: 16290000",
            "Indígena",
            "BRAUNA",
            "Rural",
            "Penapolis",
            "Av. Álvaro Gomes, 181a - Parque Res. Monreal, Penápolis - SP, 16300-000",
            "Penapolis",
            29.76,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-21.5655098, -50.31747818",
            "-21.4327, -50.0766",
            "PENAPOLIS",
            "Escola indígena em zona rural",
        ],
        [
            "ESCOLA ESTADUAL INDIGENA  ALDEIA MAENDUA PORA",
            "DO ARIRI, SANTA MARIA, CEP: 11990000",
            "Indígena",
            "CANANEIA",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            66.48,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-25.03816032, -48.14419937",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA SANTA CRUZ",
            "PARQUE ESTADUAL DA ILHA DO CARDOSO, SN, ILHA DO CARDOSO, CEP: 11990000",
            "Indígena",
            "CANANEIA",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            70.27,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-25.1335907, -47.9416008",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA RIO BRANCO II",
            "ALDEIA RIO BRANCO II, SN, RIO BRANCO II, CEP: 11990000",
            "Indígena",
            "CANANEIA",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            61.75,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-25.03256035, -48.04067993",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA TAKUARI TY",
            "BAIRRO ACARAU, SN, ACARAU, CEP: 11990000",
            "Indígena",
            "CANANEIA",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            57.20,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-25.01310921, -47.94667816",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA TAQUARI",
            "BAIRRO TAQUARI, SN, TAQUARI, CEP: 11960000",
            "Indígena",
            "ELDORADO",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            36.66,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.46722031, -48.19955826",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA PINDO TY",
            "ALDEIA PINDO  TY, SN, LINHA JURUBATUBA, CEP: 11930000",
            "Indígena",
            "PARIQUERA-ACU",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            27.19,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.75048065, -47.86373138",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA ARACA MIRIM",
            "RIBEIRAO VERMELHO, SN, RIBEIRAO VERMELHO, CEP: 11930000",
            "Indígena",
            "PARIQUERA-ACU",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            23.56,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.71689987, -47.87017822",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA ITAPU MIRIM",
            "BAIRRO VOTUPOCA, SN, BAIRRO VOTUPOCA, CEP: 11900000",
            "Indígena",
            "REGISTRO",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            16.38,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.51189041, -48.00183868",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA PEGUAO TY",
            "PARQUE ESTADUAL INTERVALES, SN, SAIBADELA, CEP: 11910000",
            "Indígena",
            "SETE BARRAS",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            53.34,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.28780937, -48.30912018",
            "-24.4906, -47.8439",
            "REGISTRO",
            "Escola indígena em zona rural",
        ],
        [
            "PROJETO LAGOA SAO PAULO",
            "TEREZINHA ALMEIDA DOS SANTOS, 1005, AGROVILA 3, CEP: 19450000",
            "Quilombola/Assentamento",
            "CAIUA",
            "Rural",
            "Santo Anastacio",
            "Praça Dr. Luiz R E Silva, 59, Santo Anastácio - SP, 19360-000",
            "Santo Anastacio",
            45.34,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-21.6774292, -51.95434189",
            "-21.9758, -51.6514",
            "SANTO ANASTACIO",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "TXERU BA  E KUA  I",
            "TUPI GUARANI, 1500, BORACEIA, CEP: 11626315",
            "Indígena",
            "BERTIOGA",
            "Rural",
            "Santos",
            "Av. Senador Feijó, 54 - Centro, Santos - SP, 11015-500",
            "Santos",
            58.46,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.75160027, -45.78998947",
            "-23.9336, -46.3255",
            "SANTOS",
            "Escola indígena em zona rural",
        ],
        [
            "CLASSES VINCULADAS A EE OMAR DONATO BASSANI",
            "AGUA LIMPA, SN, CURUCUTU, CEP: 9835100",
            "Indígena",
            "SAO BERNARDO DO CAMPO",
            "Rural",
            "Sao Bernardo do Campo",
            "Rua Princesa Maria da Gloria, 176, Nova Petropolis, Sao Bernardo do Campo, SP, CEP: 9771130",
            "Sao Bernardo do Campo",
            17.41,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.85606956, -46.60800934",
            "-23.7080345, -46.5506747",
            "SAO BERNARDO DO CAMPO",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA RIO BRANCO",
            "ALDEIA RIO BRANCO, SN, RIO BRANCO, CEP: 11740000",
            "Indígena",
            "ITANHAEM",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            47.63,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.14668083, -46.80730057",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA TANGARA",
            "DE ACESSO ANTONIO CALICO, SN, ALDEIA TANGARA, CEP: 11740000",
            "Indígena",
            "ITANHAEM",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            54.57,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.16555023, -46.87303162",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "KUARAY O E A SOL NASCENTE",
            "ALDEIA ITAOCA, SN, ALDEIA ITAOCA, CEP: 11730000",
            "Indígena",
            "MONGAGUA",
            "Urbana",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            34.82,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.11581039, -46.68315125",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona urbana",
        ],
        [
            "ALDEIA AGUAPEU",
            "ALDEIA AGUAPEU, SN, AGUAPEU, CEP: 11730000",
            "Indígena",
            "MONGAGUA",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            30.58,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.08580971, -46.65306091",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA NHAMANDU MIRIM",
            "AREA RURAL, KM 339, AREA RURAL DE PERUIBE, CEP: 11789899",
            "Indígena",
            "PERUIBE",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            72.98,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.28722954, -47.00923157",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA BANANAL",
            "ARMANDO CUNHA, SN, BAMBU, CEP: 11776314",
            "Indígena",
            "PERUIBE",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            69.26,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.26161003, -46.98276901",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA PIACAGUERA",
            "ALDEIA PIACAGUERA, SN, SANTA CRUZ, CEP: 11750000",
            "Indígena",
            "PERUIBE",
            "Rural",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            61.67,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.24653053, -46.90629959",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona rural",
        ],
        [
            "ALDEIA TEKOA MIRIM",
            "SERRA DA LEOA, SN, ALDEIA TEKOA MIRIM, CEP: 11717900",
            "Indígena",
            "PRAIA GRANDE",
            "Urbana",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            15.16,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.00324059, -46.52542877",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona urbana",
        ],
        [
            "ALDEIA DE PARANAPUA",
            "PRAIA DE PARANAPUA, SN, ALDEIA PARANAPUA, CEP: 11325010",
            "Indígena",
            "SAO VICENTE",
            "Urbana",
            "Sao Vicente",
            "Rua Joao Ramalho, 378, Centro, Sao Vicente, SP, CEP: 11310050",
            "Sao Vicente",
            1.85,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.98343086, -46.3825798",
            "-23.9668, -46.3816",
            "SAO VICENTE",
            "Escola indígena em zona urbana",
        ],
        [
            "KRUKUTU",
            "GRANJA SAIKI, 1693, BARRAGEM, CEP: 4895000",
            "Indígena",
            "SAO PAULO",
            "Urbana",
            "Sul 3",
            "Avenida Alcindo Ferreira, 4 - Parque do Castelo, São Paulo - SP, 04803-170",
            "São Paulo",
            19.00,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.86470985, -46.62084961",
            "-23.7144, -46.7097",
            "SUL 3",
            "Escola indígena em zona urbana",
        ],
        [
            "INDIGENA GUARANI GWYRA PEPO",
            "JOAO LANG, 153, CIPO DO MEIO, CEP: 4895070",
            "Indígena",
            "SAO PAULO",
            "Urbana",
            "Sul 3",
            "Avenida Alcindo Ferreira, 4 - Parque do Castelo, São Paulo - SP, 04803-170",
            "São Paulo",
            18.06,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-23.86746979, -46.65039063",
            "-23.7144, -46.7097",
            "SUL 3",
            "Escola indígena em zona urbana",
        ],
        [
            "INDIA VANUIRE",
            "POSTO INDIGENA B, SN, PONTE ALTA, CEP: 17630000",
            "Indígena",
            "ARCO-IRIS",
            "Rural",
            "Tupa",
            "Praca Praca da Bandeira, 900, Centro, Tupa, SP, CEP: 17600380",
            "Tupa",
            20.40,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-21.79439926, -50.38648987",
            "-21.9349129, -50.5141255",
            "TUPA",
            "Escola indígena em zona rural",
        ],
        [
            "BAIRRO DE BOMBAS",
            "BAIRRO BOMBAS DE BAIXO SN",
            "Quilombola/Assentamento",
            "IPORANGA",
            "Rural",
            "Apiai",
            "APIAI - SP",
            "APIAI",
            21.99,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.60935974, -48.65967178",
            "-24.51111, -48.84222",
            "Apiai",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "BAIRRO BOMBAS DE CIMA",
            "BAIRRO BOMBAS DE CIMA SN",
            "Quilombola/Assentamento",
            "IPORANGA",
            "Rural",
            "Apiai",
            "APIAI - SP",
            "APIAI",
            21.99,
            "Baixa (<50km)",
            "BAIXA - Adequada",
            "-24.60933304, -48.65969086",
            "-24.51111, -48.84222",
            "Apiai",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "FAZENDA DA CAIXA",
            "CASA DA FARINHA S/N",
            "Quilombola/Assentamento",
            "UBATUBA",
            "Rural",
            "Caraguatatuba",
            "Avenida Alagoas, 539, Indaia, Caraguatatuba, SP, CEP: 11665159",
            "Caraguatatuba",
            67.76,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-23.34110069, -44.83760834",
            "-23.6204, -45.4132",
            "Caraguatatuba",
            "Escola quilombola/assentamento em zona rural",
        ],
        [
            "MARIA ANTONIA CHULES PRINCS",
            "BENEDITO PASCOAL DE FRANCA KM 37 KM 111",
            "Quilombola/Assentamento",
            "ELDORADO",
            "Rural",
            "Registro",
            "Rua Vitória, 465 - Jardim America, Registro - SP, 11900-000",
            "Registro",
            58.21,
            "Média (50-100km)",
            "BAIXA - Adequada",
            "-24.60128975, -48.40626144",
            "-24.4906, -47.8439",
            "Registro",
            "Escola quilombola/assentamento em zona rural",
        ],
    ]

    # Colunas do DataFrame
    colunas = [
        "Nome_Escola",
        "Endereco_Escola",
        "Tipo_Escola",
        "Cidade_Escola",
        "Zona",
        "DE_Responsavel",
        "Endereco_Diretoria",
        "Cidade_Diretoria",
        "Distancia_KM",
        "Classificacao",
        "Prioridade",
        "Coordenadas_Escola",
        "Coordenadas_Diretoria",
        "DE_Codigo",
        "Observacoes",
    ]

    # Criar DataFrame
    df = pd.DataFrame(dados_escolas, columns=colunas)

    # Processar coordenadas
    print("🔄 Processando coordenadas...")

    def extrair_coordenadas(coord_str):
        """Extrai latitude e longitude de string de coordenadas"""
        try:
            coords = coord_str.replace(",", "").split()
            if len(coords) >= 2:
                lat = float(coords[0])
                lon = float(coords[1])
                return lat, lon
        except:
            pass
        return None, None

    # Adicionar colunas de coordenadas separadas
    df[["Latitude_Escola", "Longitude_Escola"]] = df["Coordenadas_Escola"].apply(
        lambda x: pd.Series(extrair_coordenadas(x))
    )

    df[["Latitude_Diretoria", "Longitude_Diretoria"]] = df[
        "Coordenadas_Diretoria"
    ].apply(lambda x: pd.Series(extrair_coordenadas(x)))

    # Verificar estatísticas
    total_escolas = len(df)
    escolas_indigenas = len(df[df["Tipo_Escola"] == "Indígena"])
    escolas_quilombolas = len(df[df["Tipo_Escola"] == "Quilombola/Assentamento"])
    diretorias_unicas = df["DE_Responsavel"].nunique()

    print(f"📊 Total de escolas processadas: {total_escolas}")
    print(f"🏛️ Escolas indígenas: {escolas_indigenas}")
    print(f"🏡 Escolas quilombolas/assentamentos: {escolas_quilombolas}")
    print(f"🏢 Diretorias de ensino responsáveis: {diretorias_unicas}")

    # Verificar KOPENOTI
    kopenoti = df[df["Nome_Escola"].str.contains("KOPENOTI", na=False, case=False)]
    if not kopenoti.empty:
        distancia_kopenoti = kopenoti.iloc[0]["Distancia_KM"]
        print(f"🎯 KOPENOTI: {distancia_kopenoti} km (validação: 27.16 km)")
        if abs(distancia_kopenoti - 27.16) < 0.1:
            print("✅ Validação KOPENOTI: CORRETO")
        else:
            print("❌ Validação KOPENOTI: INCORRETO")

    # Salvar arquivo Excel atualizado
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    arquivo_saida = f"dados/excel/distancias_escolas_diretorias_completo_63_ATUALIZADO_{timestamp}.xlsx"

    try:
        df.to_excel(arquivo_saida, index=False)
        print(f"✅ Arquivo Excel salvo: {arquivo_saida}")

        # Substituir arquivo principal
        arquivo_principal = (
            "dados/excel/distancias_escolas_diretorias_completo_63_corrigido.xlsx"
        )
        if os.path.exists(arquivo_principal):
            # Backup do atual
            backup_file = f"dados/excel/distancias_escolas_diretorias_completo_63_corrigido_BACKUP_{timestamp}.xlsx"
            os.rename(arquivo_principal, backup_file)
            print(f"💾 Backup criado: {backup_file}")

        # Copiar novo arquivo como principal
        import shutil

        shutil.copy2(arquivo_saida, arquivo_principal)
        print(f"🔄 Arquivo principal atualizado: {arquivo_principal}")

        return True, df

    except Exception as e:
        print(f"❌ Erro ao salvar arquivo: {e}")
        return False, None


def main():
    """Função principal"""
    print("🔄 PROCESSAMENTO COMPLETO DOS DADOS DAS 63 ESCOLAS")
    print("=" * 80)
    print(f"📅 Data: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print()

    # Processar dados
    sucesso, df = processar_dados_completos_63_escolas()

    if sucesso:
        print("\n🎯 ATUALIZAÇÃO CONCLUÍDA COM SUCESSO!")
        print("=" * 50)
        print("✅ Arquivo Excel principal atualizado")
        print("✅ Dados das 63 escolas processados")
        print("✅ Coordenadas validadas")
        print("✅ Distâncias Haversine confirmadas")
        print()
        print("🚀 PRÓXIMOS PASSOS:")
        print("1. Executar: python scripts/atualizar_relatorios_completos.py")
        print("2. Validar: python scripts/repositorio_central.py")
        print("3. Visualizar: dashboard/dashboard_integrado.html")
    else:
        print("\n❌ FALHA NA ATUALIZAÇÃO!")
        print("Verifique os logs de erro acima.")

    return sucesso


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
